#!/bin/bash

#!/bin/bash

#url -i -H "Content-Type: application/json" -X POST -d '{"id": ${1} }' http://localhost:5000/#consumer

if [ $1 == '1' ]; then
    curl -i -H "Content-Type: application/json" -X POST -d '{"id": "1"}' http://localhost:5000/consumer
fi

if [ $1 == '2' ]; then
    curl -i -H "Content-Type: application/json" -X POST -d '{"id": "2"}' http://localhost:5000/consumer
fi

if [ $1 == '3' ]; then
    curl -i -H "Content-Type: application/json" -X POST -d '{"id": "3"}' http://localhost:5000/consumer
fi

if [ $1 == '4' ]; then
    curl -i -H "Content-Type: application/json" -X POST -d '{"id": "4"}' http://localhost:5000/consumer
fi

#if [ $1 == 'historico' ]; then#
#	curl -i http://localhost:5000/historico
#fi
